Repository ARM-software/CMSIS-NN, pull requests merged in 2023-01, with the labels that each got.

#33 Optimize LSTM kernel
  Include/arm_nn_math_types.h
  Include/arm_nnsupportfunctions.h
  README.md
  Source/BasicMathFunctions/arm_elementwise_mul_s16_s8.c
  Source/NNSupportFunctions/arm_nn_lstm_update_cell_state_s16.c
  Source/NNSupportFunctions/arm_nn_vec_mat_mul_result_acc_s8.c
Labels: feature

#34 Use SMULTT/SMULBB for elementwise mul
  Source/BasicMathFunctions/arm_elementwise_mul_s16.c
  Source/BasicMathFunctions/arm_elementwise_mul_s8.c
Labels: improvement

#36 Fix error in optimization function selection
  Source/ConvolutionFunctions/arm_depthwise_conv_wrapper_s16.c
  Tests/UnitTest/TestCases/test_arm_depthwise_conv_s16/Unity/unity_test_arm_depthwise_conv_s16.c
  Tests/UnitTest/TestCases/test_arm_depthwise_conv_s16/test_arm_depthwise_conv_s16.c
Labels: bug

#39 Remove dependency to CMSIS-Core
  .clang-format
  ARM.CMSIS-NN.pdsc
  CMakeLists.txt
  Include/Internal/arm_nn_compiler.h
  Include/arm_nn_math_types.h
  Include/arm_nn_types.h
  Include/arm_nnsupportfunctions.h
  README.md
  Source/ActivationFunctions/arm_relu_q15.c
  Source/ActivationFunctions/arm_relu_q7.c
  Source/BasicMathFunctions/arm_elementwise_add_s8.c
  Source/BasicMathFunctions/arm_elementwise_mul_s16.c
  Source/BasicMathFunctions/arm_elementwise_mul_s16_s8.c
  Source/BasicMathFunctions/arm_elementwise_mul_s8.c
  Source/ConvolutionFunctions/arm_convolve_1_x_n_s8.c
  Source/ConvolutionFunctions/arm_convolve_1x1_s8.c
  Source/ConvolutionFunctions/arm_convolve_1x1_s8_fast.c
  Source/ConvolutionFunctions/arm_convolve_fast_s16.c
  Source/ConvolutionFunctions/arm_convolve_s8.c
  Source/ConvolutionFunctions/arm_depthwise_conv_3x3_s8.c
  Source/ConvolutionFunctions/arm_depthwise_conv_fast_s16.c
  Source/ConvolutionFunctions/arm_depthwise_conv_s8_opt.c
  Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_s8_s16.c
  Source/NNSupportFunctions/arm_nn_lstm_update_cell_state_s16.c
  Source/NNSupportFunctions/arm_nn_mat_mul_core_1x_s8.c
  Source/NNSupportFunctions/arm_nn_mat_mul_kernel_s16.c
  Source/NNSupportFunctions/arm_nn_mat_mult_nt_t_s8.c
  Source/NNSupportFunctions/arm_nn_vec_mat_mul_result_acc_s8.c
  Source/NNSupportFunctions/arm_nn_vec_mat_mult_t_s16.c
  Source/NNSupportFunctions/arm_nn_vec_mat_mult_t_s8.c
  Source/NNSupportFunctions/arm_nn_vec_mat_mult_t_svdf_s8.c
  Source/NNSupportFunctions/arm_q7_to_q15_with_offset.c
  Source/PoolingFunctions/arm_avgpool_s16.c
  Source/PoolingFunctions/arm_avgpool_s8.c
  Source/SVDFunctions/arm_svdf_s8.c
  Source/SVDFunctions/arm_svdf_state_s16_s8.c
  Source/SoftmaxFunctions/arm_nn_softmax_common_s8.c
  Source/SoftmaxFunctions/arm_softmax_s16.c
  Source/SoftmaxFunctions/arm_softmax_s8.c
  Source/SoftmaxFunctions/arm_softmax_u8.c
  Tests/UnitTest/CMakeLists.txt
  Tests/UnitTest/README.md
Labels: improvement

#41 Unroll loop for GCC
  Source/NNSupportFunctions/arm_nn_vec_mat_mult_t_s8.c
Labels: improvement
